import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>index</p>
        <button
          type="button"
          onClick={() => router.push("/prerendered/getserversideprops")}
        >
          Click me
        </button>
      </main>
    </div>
  );
};

export default Home;
